侵入禁止系のシナリオテスト追加
SSL-Roots/consai_ros2 pull request #194
Opened 2024-03-28 14:57 UTC by nabekuro0104

- 相手ボールプレースメント中に侵入禁止エリアに入らない

2024-04-04 20:55 UTC, ShotaAk approved these changes
コード見ました。コメントの確認お願いします

2024-04-04 20:55 UTC, ShotaAk commented on tests/test_scenario_penalty.py
> +    assert success is True
フラグを逆にしてほしいです。

この実装だと、「エリアから全員が一瞬でも離れたらテスト終了」という処理になっています。

テストとしては「n秒間、エリアへの侵入がなかったらテスト終了」としてほしいです。

なので、コールバック関数は「1台でも侵入したらTrueを返す」ようにしてください。
判定のところで、get_result()がtrueだったらテスト失敗、としてください。

2024-04-04 20:55 UTC, ShotaAk commented on tests/test_scenario_penalty.py
> +# def test_インプレイ中にディフェンスエリアに侵入しないこと(rcst_comm: Communication):
こちら、テスト失敗すること確認しました。（回避せねば、、、）

2024-04-04 20:55 UTC, ShotaAk commented on tests/test_scenario_penalty.py
> +def test_ボールプレースメント時に進入禁止エリアに侵入しないこと(rcst_comm: Communication):
このファイルはペナルティ用のテストを書くものなので、移動をお願いします。

test_obstacle_avoidance.pyというファイルを作り、そこに移動してください。

2024-04-04 20:55 UTC, ShotaAk commented on tests/test_scenario_penalty.py
> +# def test_インプレイ中にディフェンスエリアに侵入しないこと(rcst_comm: Communication):
test_obstacle_avoidance.pyというファイルを作り、そこに移動してください。

2024-04-04 20:57 UTC, ShotaAk requested changes
↑修正お願いします

2024-04-05 14:29 UTC, nabekuro0104 reviewed
@ShotaAk 修正しました〜

2024-04-05 14:29 UTC, nabekuro0104 commented on tests/test_scenario_penalty.py
> +def test_ボールプレースメント時に進入禁止エリアに侵入しないこと(rcst_comm: Communication):
移動しますた

2024-04-05 14:29 UTC, nabekuro0104 commented on tests/test_scenario_penalty.py
> +# def test_インプレイ中にディフェンスエリアに侵入しないこと(rcst_comm: Communication):
つらみ確認しますた

2024-04-05 14:29 UTC, nabekuro0104 commented on tests/test_scenario_penalty.py
> +# def test_インプレイ中にディフェンスエリアに侵入しないこと(rcst_comm: Communication):
移動しますた

2024-04-05 14:29 UTC, nabekuro0104 commented on tests/test_scenario_penalty.py
> +    assert success is True
判定を修正しました。

2024-04-05 19:58 UTC, ShotaAk approved these changes
LGTM！

test_scenario_***という名前にしないとCIでテスト実行されないので、
ファイル名変えときます。

2024-04-05 20:43 UTC, merged