Transクラスの実装とテストの作成
SSL-Roots/consai_ros2 pull request #55
Opened 2023-04-28 16:54 UTC by uchikun2493

consai2に実装されていたtransクラス（といくつかの関数）を移植
- geometry_tools.py
  - consai2のtool.pyの移植版
  - consai2ではPose2()を座標に使っていたが今回はリストで実装
- test_geometry_tools.py
  - geometry_tools.pyのテストコード

2023-04-29 23:49 UTC, ShotaAk reviewed
良いと思います！コメントしたので確認お願いします

2023-04-29 23:49 UTC, ShotaAk commented on consai_examples/tests/test_geometry_tools.py
> +import pytest
このテストファイルをcolcon testコマンドでテストできるように、CMakeListsに1行追記お願いします。

https://github.com/SSL-Roots/consai_ros2/blob/b5256af08073560abad72e4371d8e2e2619b56ad/consai_examples/CMakeLists.txt#L57

2023-04-30 05:11 UTC, ShotaAk requested changes
typoがありました

2023-04-30 05:11 UTC, ShotaAk commented on consai_examples/CMakeLists.txt
> +  ament_add_pytest_test(test_geometory_tools tests/test_geometory_tools.py)
```suggestion
  ament_add_pytest_test(test_geometry_tools tests/test_geometry_tools.py)
```

2023-04-30 05:14 UTC, uchikun2493 commented on consai_examples/CMakeLists.txt
> +  ament_add_pytest_test(test_geometory_tools tests/test_geometory_tools.py)
本当だ，失礼

2023-04-30 07:12 UTC, merged